pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - label=merge
      - label!=do-not-merge
      - label!=do-not-merge/work-in-progress
      - label!=do-not-merge/hold
    actions:
      merge:
        method: squash
        strict: true
