pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
      - label=merge
      - label!=do-not-merge
      - label!=do-not-merge/work-in-progress
      - label!=do-not-merge/hold
    actions:
      merge:
        method: squash
        strict: true
      delete_head_branch: {}
  - name: backport patches to stable branch
    conditions:
      - base=master
      - label=backport
    actions:
      backport:
        branches:
          - release