name: Bug report
description: Report a bug to help us improve Istio
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      placeholder: Tell us what issues you ran into
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: Include the output of `istioctl version`, `kubectl version --short`, and `helm version --short` (if you used Helm)
      render: prose
    validations:
      required: true
  - type: checkboxes
    id: area
    attributes:
      label: Affected product area
      options:
      - label: "Performance and Scalability"
      - label: "Extensions and Telemetry"
      - label: "Test and Release"
  - type: checkboxes
    id: security
    attributes:
      label: Is this the right place to submit this?
      description: |-
        This is used to report product bugs:
        To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities>
        To ask questions about how to use Istio, please visit <https://discuss.istio.io>
      options:
        - label: "This is not a security vulnerability"
          required: true
        - label: "This is not a question about how to use Istio"
          required: true
